type = "webpack"
name = "slack-file-share"
account_id = "ACCOUNT_ID"
zone_id = "ZONE_ID"
workers_dev = false

route = "ROUTE"
kv-namespaces = [
    { binding = "SLACK_COMMON", id = "SLACK_COMMON_KV_ID"}
]